import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarDemo from "@/components/Navbar";
import HeroParallaxDemo from "@/components/Hero";
import Mac from "@/components/Mac";
import StickyScroll from "@/components/Stickyscroll";
import Globe from "@/components/Globe";
import AniamtedPin from "@/components/Animatedpin";
import Footer from "@/components/ui/footer"
import Price from "@/components/ui/price"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Forge - Web Design for Local Businesses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className={inter.className}>
      {<NavbarDemo/>}
      {<HeroParallaxDemo/>}
      {<Mac/>}
      {<StickyScroll/>}
      {<Price/>}
      {<AniamtedPin/>}
      {<Globe/>}
      {<Footer/>}
      </body>
    </html>
    </>
  );
}
